# Change these first
owner: TalkaOrg # Your GitHub organization or username, where this repository lives
repo: talka-status-dashboard # The name of this repository

sites:
  - name: Talka Insights
    url: https://insights.talka.ai
  - name: Talka Intelligence Service
    url: https://models-results.talka.ai
  - name: Talka Salesforce Service
    url:  https://salesforce-platform.talka.ai
  - name: Talka Hubspot Service
    url:  https://hubspot-platform.talka.ai

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: talka.ai
  baseUrl: /talka-status-dashboard
  logoUrl: https://cdn.prod.website-files.com/61697b680aeeaeba1f87f13b/6319e87dd83f5031cf86a5a8_site-default.svg
  name: Talka Service Monitor
  introTitle: "Service Status Monitor for Talka"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
